version: '3'

services:
  # Django application
  project:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/app/project
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"

  # PostgreSQL database
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A project worker --loglevel=info
    volumes:
      - ./project:/app/project
    depends_on:
      - redis
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

  # Celery beat
  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A project beat --loglevel=info
    volumes:
      - ./project:/app/project
    depends_on:
      - redis
    environment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
