# Generated by Django 5.0.3 on 2024-03-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('can_edit_own_message', 'User can edit own message'),)},
        ),
    ]
