# Generated by Django 5.0.3 on 2024-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='service_msg',
            field=models.BooleanField(default=False),
        ),
    ]
